### ISSUE TITLE
geometry type not implemented

### ISSUE THREAD

**Issue by Monduiz** [mapbox/tile-reduce#103]
When using geojson I get the error: Geometry type not implemented.

Is geometryCollection accepted?

Geojson is like this: 
{"type", "geometryCollection", "geometries":[
{"type", "polygon", "coordinates":[]},
{"type", "polygon", "coordinates":[]}
]};

**Comment by mourner** [comment]
GeometryCollection is written with the capital G.

**Comment by mourner** [comment]
Same for `Polygon`. Please use http://geojsonlint.com/

**Comment by Monduiz** [comment]
Yes, and the typos are only in my comment, not in my code. In the script, it is written as it should.
I didnt copy and pasted the original geojson here because its large, I just gave an idea of its structure.

**Comment by mourner** [comment]
@Monduiz then you must provide us with a minimal test case that reproduces the issue while being valid GeoJSON.

**Comment by Monduiz** [comment]
Will, do. I provided too little.
