### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by morganherlocker** [mapbox/tile-reduce#2]
We should have tests for:
- [x] [counting features](https://github.com/mapbox/tile-reduce/tree/master/test/count)
- [x] [road diffing](https://github.com/mapbox/tile-reduce/tree/master/test/diff)
- [x] mass trace missing road identification
- [x] [unconnected major roads](https://github.com/mapbox/tile-reduce/tree/master/test/disconnect)
- [ ] one-way check
- [ ] dead end one ways
- [ ] missing speed limits
  - [ ] or speed limits significantly different from traces
- [ ] kinks
- [ ] self intersecting ways
- [x] [count miles of roads](https://github.com/mapbox/tile-reduce/tree/master/test/miles)
- [x] [count number of buildings](https://github.com/mapbox/tile-reduce/tree/master/test/buildings)

What else should we test?

- map matching/ trace snapping aggregation

@aaronlidman @MateoV @lxbarth

**Comment by aaronlidman** [comment]
@ericfischer Is working on one-way check this week.
@aaronlidman Is working on counting road/path miles and buildings this week

**Comment by morganherlocker** [comment]
We actually have quite a few functional tests now. Since what we are really testing is tile-reduce, rather than the specific use cases, I think we can probably move on to unit tests at this point. The functional tests here will provide a good starting point for the tests of the actual implementations of these tasks.
