### ISSUE TITLE
support local (mbtiles) source of vector tiles

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tile-reduce#20]
I think it would be pretty straightforward, using tilelive + node-mbtiles & node-tilejson, to generalize [getVectorTile][0] to either backend source.

[0]: https://github.com/mapbox/tile-reduce/blob/master/worker.js#L32-L69

**Comment by morganherlocker** [comment]
@anandthakker How about rendering your vector tiles once locally and serving them with something like [tilestache](http://tilestache.org/doc/)?  tile-reduce would allow you to point to a locally hosted tile server. The reason I am reluctant to allow local file access directly, is that it would cause an impedance mismatch between browser/desktop/server processing. Neither browsers nor server clusters would have access to an mbtiles file. Ideally, tile-reduce works exactly the same across platforms, and with consistent performance profiles.

**Comment by anandthakker** [comment]
@morganherlocker Ah, okay--yeah, that makes plenty of sense to me.  Closing!
