### ISSUE TITLE
is tilereduce a class or a function?

### ISSUE THREAD

**Issue by tmcw** [mapbox/tile-reduce#34]
* classes should be uppercased and initialized
* functions should be lowercased

The example has a confusing invocation of tilereduce: 

```js
var TileReduce = new require('tile-reduce');
...
var tilereduce = TileReduce(bbox, opts);
```

A more common expectation would be

```js
var TileReduce = require('tile-reduce');
...
var tilereduce = new TileReduce(bbox, opts);
```

**Comment by mourner** [comment]
Currently it's a factory that creates an `EventEmitter` object, so it can be used without `new` anywhere. I would consider making it a proper class that inherits `EventEmitter` for code clarity though (preserving the newless API).

**Comment by mourner** [comment]
Will be fixed as a part of https://github.com/mapbox/tile-reduce/pull/46.
