### ISSUE TITLE
Error in example - wrong road layer

### ISSUE THREAD

**Issue by rustyb** [mapbox/tile-reduce#37]
Howdy Folks - I just noticed a small error in the example code where the roads layer from mapbox-streets is wrong:

```layers: ['roads']``` should in fact be ```layers: ['road']```
 
Similarly in ```buffer.js``` it should be:

```
module.exports = function (tileLayers, opts, done){
  var road = tileLayers.streets.road;
  var bufferedRoad = turf.buffer(road, 20, 'meters');
  done(null, bufferedRoad);
}
```

**Comment by morganherlocker** [comment]
thanks @rustyb!

https://github.com/mapbox/tile-reduce/commit/02a9645369ad39f4999eec10bb3c325a47df7cdd
