### ISSUE TITLE
Factor out vector tile parsing

### ISSUE THREAD

**Issue by willwhite** [mapbox/tile-reduce#39]
We are starting to use tile-reduce for more than just vector tile processing. To acomplish this we have to [remove VT parsing code](https://github.com/mapbox/tile-reduce/commit/795ec51e6dd8577dca53bddc4c51d0b65d1d7a7d#diff-8a5b5909f5b3ce1a25a1c499ab30da2cL51) and [whatever parsing code we want](https://github.com/mapbox/tile-reduce/commit/795ec51e6dd8577dca53bddc4c51d0b65d1d7a7d#diff-8a5b5909f5b3ce1a25a1c499ab30da2cR40). Can tile-reduce simply act as a fetching mechanism and return pass raw data to the processors for custom parsing?

/cc @lbud

**Comment by mourner** [comment]
I'd love to see that too. It's useful for vector tiles as well, e.g. when we want to parse vector pbfs lazily and process geometries directly without GeoJSON conversion for performance.

**Comment by mourner** [comment]
Happening as a part of https://github.com/mapbox/tile-reduce/pull/46
