### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mourner** [mapbox/tile-reduce#42]
When you're not accumulating results on `reduce` events, the memory consumption still creeps up so you can easily go out of memory on a large number of tiles. This doesn't look right — there's probably a big memory leak somewhere.

**Comment by mourner** [comment]
Found the cause. Asynchronous `zlib.unzip` leaks memory when you call it many thousands of times at once. Switching to `unzipSync` [here](https://github.com/mapbox/tile-reduce/blob/be8be60d1c575514a9d4bda74d2d6ca6ab5f6854/index.js#L84) fixes the leak (only supported by node 0.12+).

In theory, `maxrate` could help with this, but it is not set by default for `mbtiles` sources. But even if you set it, maxrate is broken anyway #44.

To fix it the proper way, we need to ditch maxrate completely and instead switch to a global queue with a max limit, so that only a certain number of tiles is processed at the same time, and a new tile doesn't start to be even loaded or parsed from MBTiles before we completed a previous tile.

**Comment by mourner** [comment]
cc @MateoV @morganherlocker @tcql

**Comment by morganherlocker** [comment]
nice catch!

**Comment by mourner** [comment]
I was wrong, `unzipSync` does not fix the memory issue entirely — memory still creeps up on long-running tasks. However the next-gen tile-reduce should solve all memory problems.

**Comment by mourner** [comment]
Will be fixed by https://github.com/mapbox/tile-reduce/pull/46.
