### ISSUE TITLE
maxrate is broken

### ISSUE THREAD

**Issue by mourner** [mapbox/tile-reduce#44]
@MateoV this commit https://github.com/mapbox/tile-reduce/commit/f945449d03592c9e1be09d0ffa218caba6362969 broke maxrate.

On [this line](https://github.com/mapbox/tile-reduce/blob/be8be60d1c575514a9d4bda74d2d6ca6ab5f6854/index.js#L214), `getTile(data)` gets immediately called for all tiles, an its return value (undefined) gets served to `rateLimit` which does nothing.

cc @tcql

**Comment by aaronlidman** [comment]
This was previously in place to prevent hitting our APIs too hard.

Is there any reason we would want to rate limit locally?

**Comment by mourner** [comment]
@aaronlidman yes, see #42 (it may help)

**Comment by morganherlocker** [comment]
I just want to also add here that we still support remote sources, so this is important. Many tasks do make sense over HTTP (cpu heavy jobs like image analysis, where having all the data locally is not practical or necessary).

**Comment by mourner** [comment]
Fixed in #46
