### ISSUE TITLE
Passing options to workers

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tile-reduce#48]
I'm thinking about using tile-reduce to power a little utility module, where I'd need to pass options along from the main process to the workers.  Could the `map` module get passed the serialized tile reduce options as one of its initial args?

**Comment by mourner** [comment]
Yes, good idea! I suppose #18 means the same too.

**Comment by anandthakker** [comment]
Hmm, not sure what the best API for this is, though.  If handling the options requires a bit of up-front work, it would not be ideal to just add `options` as another arg to the `map` function.  I guess the `map` module could be changed to export a function that takes options and returns the actual map function -- it's an extra bit of indirection, but pretty typical for Node modules

**Comment by mourner** [comment]
@anandthakker hmm, can you give an example of upfront work? Maybe we should just pass options to the map function.

**Comment by anandthakker** [comment]
@mourner Sure -- this is pretty idiosyncratic, but my main module accepts a big map like `{ [layername]: { [propertyname]: aggregationString } }`, and the workers use each `aggregationString` to construct an aggregation function which they'll apply to each feature they encounter.  Building the aggregation function isn't especially complicated--it's essentially a `Function.bind`--but it seems like that's overhead that would add up.

**Comment by mikelmaron** [comment]
> "Maybe we should just pass options to the map function."

Please! @mourner, any movement? I'm looking to try an [osmlint processor](https://github.com/osmlab/osmlint/tree/master/processors) that parses josm preset XML and tests how features' tags match against it.

**Comment by mourner** [comment]
@mikelmaron does this use case need runtime options? Could you just parse XML at the top of the map script (outside of the function)?

**Comment by mikelmaron** [comment]
@mourner runtime option is path to the josm preset file

**Comment by mourner** [comment]
@anandthakker how about we just pass the options as arguments to the worker and then expose them as something like `global.mapOptions` (before requiring the map function in the worker)?

**Comment by anandthakker** [comment]
Yep, that seems workable.

**Comment by mourner** [comment]
Done.
