### ISSUE TITLE
npm test fails under Windows

### ISSUE THREAD

**Issue by jingsam** [mapbox/tile-reduce#58]
I run `npm test` on tile-reduce 3.0. It fails on Windows 10 with node v5.1.0, while success on Ubuntu. It is strange. Here is the error message:

```
  1) test/test.count.js count implementation, mbtiles cover found all features in overlapping mbtiles:

      Error: found all features in overlapping mbtiles
      + expected - actual

      -0
      +36597

      at EventEmitter.<anonymous> (test\test.count.js:53:7)
      at shutdown (src\index.js:136:8)
      at reduce (src\index.js:126:36)
      at ChildProcess.handleMessage (src\index.js:47:25)
      at handleMessage (internal/child_process.js:686:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

  2) test/test.count.js count implementation, explicit mbtiles cover found all features in overlapping mbtiles:

      Error: found all features in overlapping mbtiles
      + expected - actual

      -0
      +36597

      at EventEmitter.<anonymous> (test\test.count.js:72:7)
      at shutdown (src\index.js:136:8)
      at reduce (src\index.js:126:36)
      at ChildProcess.handleMessage (src\index.js:47:25)
      at handleMessage (internal/child_process.js:686:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)

  3) test/test.count.js count implementation, tileStream cover found all features in listed tiles:

      Error: found all features in listed tiles
      + expected - actual

      -0
      +16182

      at EventEmitter.<anonymous> (test\test.count.js:91:7)
      at shutdown (src\index.js:136:8)
      at reduce (src\index.js:126:36)
      at ChildProcess.handleMessage (src\index.js:47:25)
      at handleMessage (internal/child_process.js:686:10)
      at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by mourner** [comment]
I suspect that we don't handle all errors correctly, so we don't see the root cause here instead of the silent 0 result. We need to make sure that we do. @tcql @morganherlocker 

@jingsam could you help us debug this issue? Maybe putting `console.warn` in different places of `count.js` and event listeners in `index.js` and seeing if there's anything suspicious?

**Comment by tcql** [comment]
> It fails on Windows 10 

I'm suspecting something obscure with streams to forked processes. I can do a test on windows 7 sometime later today too.

**Comment by tcql** [comment]
Look like it's an issue with `binary-split` on windows. On windows 7, switching to [split](https://www.npmjs.com/package/split) makes tests pass. Let's try any track down the error and fix upstream (or look into [binary-split-streams2](https://www.npmjs.com/package/binary-split-streams2))

**Comment by mourner** [comment]
Interesting. Can you set up a minimal non-TR test case reproducing the binary-split bug? 
It's a bummer that binary-split isn't maintained, maybe we should ask Max for push access and make a new major version with streams2, Travis run on many versions etc.

**Comment by mourner** [comment]
@tcql oh, I think I have a good guess about this. The issue is not with binary-split module, but with the matcher it uses for splitting. If you create it without arguments, it uses `require('os').EOL` by default, however the system EOL probably doesn't match EOL used in MBTiles or our test tile list. Instead we should probably explicitly use Unix EOL in both.

**Comment by tcql** [comment]
@jingsam could you test this out for us? change [this line](https://github.com/mapbox/tile-reduce/blob/09b12b3738c4d1e1a5f77b504465695c88b9fe2d/src/index.js#L84) to 

```js
tileStream = db.createZXYStream().pipe(binarysplit('\n')).on('data', handleZXYLine);
```

and run `npm test` again to see if this fixes the issue

**Comment by mourner** [comment]
And possibly the same [on this line](https://github.com/mapbox/tile-reduce/blob/master/test/test.count.js#L81) (depending on git config on the Win machine).

**Comment by jingsam** [comment]
Bingo！All tests passed after corrections：
`tileStream = db.createZXYStream().pipe(binarysplit('\n')).on('data', handleZXYLine);` [on this line](https://github.com/mapbox/tile-reduce/blob/09b12b3738c4d1e1a5f77b504465695c88b9fe2d/src/index.js#L84)

`tileStream: fs.createReadStream(path.join(__dirname, 'fixtures/tilelist')).pipe(split('\n')),` [on this line](https://github.com/mapbox/tile-reduce/blob/master/test/test.count.js#L81)

**Comment by tcql** [comment]
@jingsam awesome. want to make a PR?

**Comment by jingsam** [comment]
I am not sure this [PR](https://github.com/mapbox/tile-reduce/pull/62) is compatible on other platforms

**Comment by tcql** [comment]
thanks @jingsam. The change when reading mbtiles sources should work across platforms (since the newlines seem to be explicitly coming from `createXYZStream`), but we'll have to test out the other change, where it's reading from a file. This will likely break if anybody is on windows and has their git configuration set to convert line endings to windows style breaks.

**Comment by mourner** [comment]
@tcql specifically for the test, I think we could use `split` instead of `binary-split` simply because it uses a regexp matcher rather than specific bytes.

**Comment by tcql** [comment]
@jingsam thanks! this is incorporated in [v3.0.1](https://github.com/mapbox/tile-reduce/tree/v3.0.1)

**Comment by jingsam** [comment]
Now I get "Missing plan" error:
```
  remote - raw invalid url - no server
    √ remote initialized without error
    1) missing plan
    2) missing plan

  test/test.workers.js
1..0
    workers - 1 per cpu default
      √ One worker per CPU initialized
      3) missing plan
    test/test.write.js
      count implementation, tileStream cover
        √ processed all tiles
        √ produced valid JSON output

  67 passing (1m)
  3 failing

  1) test/test.remote.js remote - raw invalid url - no server missing plan:
     missing plan


  2) test/test.remote.js missing plan:
     missing plan


  3) test/test.workers.js workers - 1 per cpu default missing plan:
     missing plan
```

error 1) and 2) appear on every test. The other missing plan errors arise randomly.

**Comment by mourner** [comment]
@jingsam :( ticketed here https://github.com/mapbox/tile-reduce/issues/65
