### ISSUE TITLE
TileReduce or Tile Reduce

### ISSUE THREAD

**Issue by lxbarth** [mapbox/tile-reduce#59]
Simple question, but we should nail it down: Should we CamelCase or just do two words? I've been using Tile Reduce in blog posts but it would make sense to follow the lead of [MapReduce](https://en.wikipedia.org/wiki/MapReduce) - as much as I'm not sure why the world ever started to CamelCase outside of programming languages ;-)

@morganherlocker @tcql @mourner ?

**Comment by mourner** [comment]
I have no strong preference here, either sounds fine.

**Comment by tcql** [comment]
`TileReduce` is canonical - it's used in the docs and matches `MapReduce`.

> as much as I'm not sure why the world ever started to CamelCase outside of programming languages

@lxbarth in my head it's always `tilereduce` because that's how I write it in code 😉

**Comment by mourner** [comment]
BTW it's a bit weird that the GH repo and NPM package is `tile-reduce` and not `tilereduce`.

**Comment by morganherlocker** [comment]
Yep, TileReduce is a play on MapReduce. For the `-` in the repo names... a bit odd perhaps, but probably not worth changing, since it would break dependencies.

**Comment by lxbarth** [comment]
👍
