### ISSUE TITLE
documentation holes

### ISSUE THREAD

**Issue by tcql** [mapbox/tile-reduce#61]
We definitely need to document `raw` - we don't even mention it right now.

Optionally, we may want to add a section about how to optimize (use raw, use rbush for lots of intersections, etc) and talk about the effect of tiles with buffers and how to generate custom mbtiles without buffers

**Comment by morganherlocker** [comment]
> We definitely need to document raw - we don't even mention it right now.

[raw:true has been documented](https://github.com/mapbox/tile-reduce/commit/5bea323df7c3a107a3ed8a164d22a9ff8353251d).

> Optionally, we may want to add a section about how to optimize (use raw, use rbush for lots of intersections, etc) and talk about the effect of tiles with buffers and how to generate custom mbtiles without buffers

I mentioned lazily parsing tiles with the `raw` option in the docs. I think getting into specific algorithm optimizations with rbush or other data structures is out of scope, and more suited to a dedicated computational geometry optimization book/guide/tutorial. Tile buffers I think are also best left to dedicated Vector Tile documentation and the tools people happen to use to create them.
