### ISSUE TITLE
failing build?

### ISSUE THREAD

**Issue by morganherlocker** [mapbox/tile-reduce#65]
https://travis-ci.org/mapbox/tile-reduce/jobs/93201091 

It looks like a build failed, but the associated PR passed.

cc @tcql

**Comment by mourner** [comment]
Just rerun and it passed. Hmm maybe a random deviation.

**Comment by tcql** [comment]
I'm getting confusing results here. 

https://travis-ci.org/mapbox/tile-reduce/jobs/93201097

This one thinks `test.count` doesn't have a test plan. Earlier it complained that `test.workers` didn't have a plan.

**Comment by mourner** [comment]
Sporadical Travis build failures seem to be fixed now by https://github.com/mapbox/tile-reduce/commit/7689fd78116a00b1c7b5d6a247df38a4b33cd3e8. @jingsam can you also please confirm on Windows?

**Comment by jingsam** [comment]
Yes, all tests have passed. Network condition may affect the tests. Since I live in China, the tests succeed using VPN and failed without VPN. Anyway, it is not the program's problem, Cheers! :clap:
