### ISSUE TITLE
Output results to mapbox studio

### ISSUE THREAD

**Issue by jingsam** [mapbox/tile-reduce#70]
Hi, I am looking for suggestions. Recently, I am using tile-reduce to do some statistics on osm-qa-tiles. I want to calculate a metric (e.g. road density) on each tile of zoom 12, then output to mapbox studio for visualization. The problem is how to store the result. As zoom 12 has 16 million tiles, using GeoJson, MBtiles, or UTF8Grids maybe too large for storage. So I hope to get some advice from you as you are experts in this field.:pray:

**Comment by mourner** [comment]
The actual number of z12 tiles for a world dataset is 2.1 million, which is more manageable. Eventually we may implement writing vector tiles as output, but currently you'd have to generate GeoJSON and then run `tippecanoe` on it. If the size is too big, you'd have to split the jobs, e.g. into regions (North America, etc.), and possibly use a lower zoom level.
