### ISSUE TITLE
awesome-tile-reduce

### ISSUE THREAD

**Issue by jingsam** [mapbox/tile-reduce#71]
I think there should be a list of awesome tile-reduce projects, such as [osm-coverage](https://github.com/mapbox/osm-coverage), [osm-sidewalker](https://github.com/mapbox/osm-sidewalker).

**Comment by morganherlocker** [comment]
I have added a [Processor Examples](https://github.com/mapbox/tile-reduce#processor-examples) section to the docs. This is not meant to be an exhaustive list, but a place to showcase non-trivial implementations that people might benefit from using or forking into something new.

Thanks @jingsam!
