### ISSUE TITLE
Tile encoding troubles for disconnected road detection

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tile-reduce#8]
What I thought before was spherical geometry precision problems I now think is really tile-encoding problems.

Example: http://www.openstreetmap.org/node/1004264211. The real location is lat="38.9347951" lon="-77.0533697"

In the through way http://www.openstreetmap.org/way/38132834 it is encoded at z12 as [-77.05332040786743,38.93477700153804], [1247,1476]

In the way that ends there http://www.openstreetmap.org/way/6054333 it is encoded at z12 as [-77.05336332321167,38.93479369264057], [1245,1475]

Or at least that's what it looks like. I would have expected tile encoding to drop nodes but not to relocate them.

**Comment by morganherlocker** [comment]
:tada: https://github.com/mapbox/tile-reduce/pull/13
