### ISSUE TITLE
Change mapOptions from global to a worker parameter

### ISSUE THREAD

**Issue by morganherlocker** [mapbox/tile-reduce#80]
This would be a breaking change. At the moment mapOptions are sent to workers as global objects. I am pretty sure this is safe, since workers should not share globals across processes, however, I think it is better to be explicit. I propose we remove the global assignment and add another parameter to our worker functions. The new interface would look like this:

```js
function(data, tile, write, opts, done) {}
```

Thoughts?

cc @tcql @mourner @aaronlidman  @MateoV

**Comment by morganherlocker** [comment]
For context, the reason I think we should do this is so that map scripts can be more testable. Loading up a global context is not possible from a typical test script.

**Comment by mourner** [comment]
The original use case for adding map options (#48) was to be able to do expensive initialization in the worker outside of the map loop (once instead of for each tile). This will get much less convenient when we move the options to the map argument, so I prefer the current approach.

**Comment by morganherlocker** [comment]
[PR here](https://github.com/mapbox/tile-reduce/pull/81)

@mourner I can see why that would be a concern, but the global makes testing parameterized code tricky. I'm not sure how much of a real performance impact there would be on a typical processor compared to the cost of decoding the vector tile (not to mention the actual processing defined by the user).

**Comment by mourner** [comment]
@morganherlocker here's an example: suppose you want to make an index of countries to do fast point-in-poly tests (like we do with OSM Coverage). Indexing is expensive, so you want to do that once for a worker — then you would load the counties GeoJSON and `which-polygon` modules at the top level of the map script, and create an index to be queried from the map function. Now suppose you don't want to hardcode a specific GeoJSON, but want to pass it as an option instead. With the current setup, it's easy and natural. But with the proposed change, you would have to keep a global state and make sure indexing is run only on the first map call, which is cumbersome. 

Another reason to keep the current API is that making mapOptions feature more cleanly testable isn't strong enough of a benefit to break the API and require rewriting all existing tile-reduce scripts, especially considering there are workarounds for testing.

**Comment by anandthakker** [comment]
@morganherlocker @mourner FWIW, the approach that would feel most natural to me would be to have the user's module export a map function _creation_ function rather than the map function itself:

```js
module.exports = function (options) {
  return function map(data, tile, etc.) {...}
}
```

To me, this would be both easy to test and remove user-side burden of caching option-processing.  Barring that, the two approaches basically seem pretty balanced to me in terms of pros and cons...

**Comment by morganherlocker** [comment]
These arguments all make sense. Thanks for the explanation(s) @mourner @anandthakker.
