### ISSUE TITLE
FP bluesky

### ISSUE THREAD

**Issue by tmcw** [mapbox/tile-reduce#84]
### The reduce function

```js
.on('reduce', function(num) {
  numFeatures += num;
})
```

The 'reduce' event isn't well-named. [reduce has a meaning](http://www.macwright.org/2015/01/03/reduce-juice.html), and this isn't it. Right now it's like a 'tileprocessed' event.

A real reduce method would be:

```js
.reduce(function(memo, num) {
  return memo + num;
}, 0);
```

This

* Avoids side-effects in the reducer method
* Doesn't rely on scope
* Allows the reducer function to be defined in a separate file

### 'reduce' script

This is what we call the javascript file that you run. This shouldn't be called the reduce script: it contains configuration, the reducer function, and a reference to the mapper function. Just call this the script.

### 'map' event

This event is more like a 'preprocess hook' than a map function, that would transform one value into another. Like the 'reduce' event, it doesn't have a meaningful return value.

This should either be renamed `.forEach`, like

```js
.forEach(function (result, tile) { 
    console.log('got a count of ' + result + ' from ' + JSON.stringify(tile));
    count++;
});
```

Which matches existing convention, or it should actually act like map:

```
.map(function (result, tile) { 
    console.log('got a count of ' + result + ' from ' + JSON.stringify(tile));
    return result + * 2;
})
.map(/ * and here you would get the new results from the previous map() method */
```

### writeData

This isn't documented, so I can't really comment on whether we're describing it properly, but the problem of 'potentially returning >1 result from a pure function without multi-return in the language' is [what flatMap solves](http://martinfowler.com/articles/collection-pipeline/flat-map.html).

---

Why should we make these changes?

* tile-reduce will be more understandable because its words will match other meanings, and be [potentially the same concept as reactive](https://baconjs.github.io/api.html)
* making mappers & reducers functional (instead of scope-hacks) will let us write them as separate files
* making reducers & mappers pure opens the door to parallelizing them in the future, and makes them testable for the first time.

**Comment by mourner** [comment]
Thanks for capturing this! For the reduce syntax, how do we get the final value, considering it's async, after running the code below?

```js
.reduce(function(memo, num) {
  return memo + num;
}, 0);
```

I agree about calling the main script a reduce script, I found this confusing as well.

**Comment by tmcw** [comment]
@mourner for synchronous code, the result of the .reduce method _is_ the value. But since this is async I think the proper syntax would be

```js
.reduce(function(memo, num) {
  return memo + num;
}, 0)
.subscribe(function(result) {
  // this is the result of the asynchronous .reduce calls
});
```

This matches the reactive syntax for this concept https://www.npmjs.com/package/baconjs#observable-subscribe - it's also sometimes called `.onValue`, either one seems fine

**Comment by tmcw** [comment]
Not seeing much interest in this.
