### ISSUE TITLE
✋ should we remove support for node 0.10

### ISSUE THREAD

**Issue by tcql** [mapbox/tile-reduce#91]
Per #90, there are some node 0.10 specific instabilities in tile-reduce. I'd like to get some feedback from folks developing & using tile-reduce to decide on deprecating node 0.10 support. 

If we drop 0.10, systems whose package manager are holding at 0.10.x will need to use [install-node](https://github.com/mapbox/install-node) or [nvm](https://github.com/creationix/nvm) to upgrade to at least node 0.12

/cc @morganherlocker @mourner @aaronlidman @tmcw @geohacker @anandthakker

**Comment by aaronlidman** [comment]
👍

**Comment by mourner** [comment]
We'll be forced to fully get off Node 0.10/0.12 by the end of the year anyway (they'll stop getting even security updates). I vote for dropping Node 0.10 support in tile-reduce now, along with 0.12.

![](https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png)
