### ISSUE TITLE
`stable` fails on travis

### ISSUE THREAD

**Issue by tcql** [mapbox/tile-reduce#92]
Looks like node 6 is `stable` on travis already, but it fails during node-gyp when installing sqlite3 dependency of node-mbtiles, because node 6 NAN requires C++11

https://travis-ci.org/mapbox/tile-reduce/jobs/126161614

Looks like we could explicitly install later versions of g++ as an apt dep in travis

**Comment by mourner** [comment]
We could also fix the source problem by providing Node6 binaries for sqlite3 node-pre-gyp.

**Comment by mourner** [comment]
cc @springmeyer
