### ISSUE TITLE
Zoom level of osm.mbtiles used in count example

### ISSUE THREAD

**Issue by bkowshik** [mapbox/tile-reduce#94]
Using tile-reduce version: `3.1.1`

#### Steps to Trigger Behavior
1: Clone `tile-reduce` with `git clone git@github.com:mapbox/tile-reduce.git`
2: `cd tile-reduce`
3: Install dependencies with `npm install`

#### Actual Behavior
4: Run count example.
```
$ node examples/count/index.js
Starting up 4 workers... Job started.
Processing 4 tiles.
4 tiles processed in 0s.
Features total: 0
```
#### Expected Behavior
5: Update `zoom` value in `index.js` from `12` to `15` and run again.
```
$ node examples/count/index.js
Starting up 4 workers... Job started.
Processing 81 tiles.
81 tiles processed in 0s.
Features total: 10098
```
The example should output a non-zero feature count when run as is.

---

I am guessing the solution is to update `osm.mbtiles` test fixture to work with zoom `15`. I would be glad to work on this if somebody could point me to related resource/documentation.

---

cc: @arunasank

**Comment by aaronlidman** [comment]
@bkowshik - Yes, changing it to 15 is the best action here. Previously: https://github.com/mapbox/tile-reduce/commit/117c44303d0b2a257b55cf4d23ba552524028068

Can you change it and submit a pull request?

Thanks for catching that.
